### ISSUE TITLE
"Click here to ship/pickup" & hide pickup location when shipping?

### ISSUE THREAD

**Issue by vqwebguy** [skyverge/wc-plugins-snippets#10]
Hi there. Is there a way to move this button in one of the visual hooks? It's hard to customize the look of that button and have it shown more visibly.
woocommerce_review_order_before_shipping

Also automatically hide "shipping via local pickup" section when Ship the item is selected? 
Our customer sometimes get confused still seeing local pickup option when they only want to ship their orders.

https://i.imgur.com/mEBoIvz.png

Thanks!
Elmer

**Comment by vqwebguy** [comment]
I think I can get away with just using CSS for the button. Can you help with hiding the block "shipping via local pickup" when Shipping is selected?

Thanks!

**Comment by bekarice** [comment]
> Can you help with hiding the block "shipping via local pickup" when Shipping is selected?

Hey @vqwebguy ! This is typically hidden by default, so sounds like there's an issue at play. Can you please [submit this to our support team](https://woocommerce.com/my-account/marketplace-ticket-form/) for assistance in debugging this? thanks!
