### ISSUE TITLE
Tracking downloads

### ISSUE THREAD

**Issue by accetturo** [skyverge/wc-plugins-snippets#2]
We are trying to track users that download files from a simple woocommerce product but our codes not working, any tips?

**Comment by bekarice** [comment]
@accetturo this repo is specific to SkyVerge extensions rather than WooCommerce, so afraid that's not something we plan to add here as we're not adding general WooCommerce snippets. thanks!

**Comment by accetturo** [comment]
Did you guys develop this addon, if so, you completely missed the download file action. We are building it now and we push it when its done if you want to share it as its a critical event for mixpanel. 

use case. Say a user is using the mixpanel + helpscout plugins. Great works wonderful, but what about the people who can't download files for tech reasons or do download them and want a refund, wouldn't it be nice to see the mixpanel event of a downloaded file rihgt in the mixpanel helpscout side panel, well, you can't do that because you guys never built out this class.
