### ISSUE TITLE
Where should I add this code?

### ISSUE THREAD

**Issue by carolallanos** [skyverge/wc-plugins-snippets#3]
Hi, sorry, I got lost, I tried adding it to my functions.php and didn't worked. Then I installed the snippets plugins and add it there, it still not sending notifications to new imported users. Am I missing something?
[https://github.com/skyverge/wc-plugins-snippets/blob/master/woocommerce-memberships/admin/notify-new-users-from-import.php]
Please help!
THANKS!

**Comment by bekarice** [comment]
hey @carolallanos [as per the notes here](https://github.com/skyverge/wc-plugins-snippets#skyverge-woocommerce-plugins), I'm afraid we can't provide support for custom snippets. I've added this to my test site and it works for me, so I'd recommend adding a mail logging filter, deactivating plugins, and switching themes to see if there's a conflict or other issue with email sending on the site. cheers!
