### ISSUE TITLE
Adding Cost to AddOn Items

### ISSUE THREAD

**Issue by atarsha** [skyverge/wc-plugins-snippets#5]
I am using the Product Addons extension for WooCommerce to upsell a specific product with additional accessories for that product. Example being "Add a case for this doodad?"

The case has a cost too, but I have no way to insert that so it shows up as all profit. Are there any plans to work with this extension?

Thank you!

**Comment by bekarice** [comment]
@atarsha thanks for reaching out here! I'm afraid Product Add-ons isn't one of our extensions at SkyVerge so we don't have any snippets available for it. [Codeable is great](http://skyverge.com/link/codeable) for these sort of customizations, though!
