### ISSUE TITLE
Date format 9-29-2017

### ISSUE THREAD

**Issue by vqwebguy** [skyverge/wc-plugins-snippets#6]
Hi there,
First of, thanks for this extension. It help me alot. 👍 

My question is formating the output date to m-dd-yyyy. I'm really not sure what to change from this snippets. I tried changing it to 'm-d-Y' but it's displaying 9/29/2017 with "/" instead of "-". I hope you could help. Thanks!

<?php // only copy if needed
/**
 * Adjusts the date format for export files from MySQL format to a custom format.
 *
 * REQUIRES v4.3.4+
 *
 * @param string $date the current formatted date
 * @param \WC_Customer_Order_CSV_Export_Generator $generator the generator instance
 * @return string the updated formatted date
 */
function sv_wc_csv_export_format_dates( $date, $generator ) {
	// in WC 3.0+ this date could be null, so leave it alone if not set
	if ( $date ) {
		switch( $generator->export_type ) {
			case 'orders':
				$date = date( 'm-d-Y', strtotime( $date ) );
			break;
			case 'customers':
				$date = date( 'Y.m.d', strtotime( $date ) );
			break;
		}
	}
	return $date;
}
add_filter( 'wc_customer_order_csv_export_format_date', 'sv_wc_csv_export_format_dates', 10, 2 );

**Comment by bekarice** [comment]
Hey @vqwebguy this is likely an issue with the spreadsheet program viewing the file -- that filter is most helpful if you're sending it automatically to another server, not viewing it manually as Excel / other readers often auto-format dates. I'd try formatting the date column in Google Drive instead: 
![screen shot 2017-10-02 at 5 10 16 pm](https://user-images.githubusercontent.com/4983547/31099632-aca0d59e-a794-11e7-8dd4-3a9ef1f6c35b.png) (use "more formats" to build the one you want)
