### ISSUE TITLE
Basket Page

### ISSUE THREAD

**Issue by djm56** [skyverge/wc-plugins-snippets#7]
Hi I am very happy with the plugin works great. We are using it to add gift wrapping. My client wanted to know if it is possible to add it to the basket (cart) page rather. I thought I would ask if not will tell them it has to be on the checkout page as the name of the plugin suggests.
Regards

**Comment by bekarice** [comment]
hey @djm56 thanks for reaching out :) I'm afraid adding this to the cart page wouldn't be very straight-forward given that you'd also need a way to stash options in the customer session and carry them over to the cart page -- so this would be do-able, but not something we plan to put any examples for.

As such, I'm going to close this one. thanks again!
