### ISSUE TITLE
Item Price

### ISSUE THREAD

**Issue by vqwebguy** [skyverge/wc-plugins-snippets#8]
Is there anyway to move/rearrange the item_price after adding it using the code written below? 

https://github.com/skyverge/wc-plugins-snippets/blob/master/woocommerce-customer-order-csv-export/add-item-price-to-order-export.php 

We're using a Microsoft based inventory system and every column has already been mapped to certain table when we import the file. Since the code written is automatically inserted after the sku, we would need to remap the rest of the column after (and do more test that'll take time)... I hope I'm being clear with my request.. :)

Also, If it make sense, I would actually like to just replace the **item_subtotal** with **item_price**

Also, I'm talking about adding the column into the **_Custom Format_** tab

Thanks for your time.

**Comment by bekarice** [comment]
Hey @vqwebguy, you'd need to change the column key it's being inserted after to use your desired position. I'm afraid we can't assist with further customization of these snippets, so we [typically recommend reaching out to Codeable](http://skyverge.com/link/codeable) for further customization. thanks!
